---
# tasks file for nginx

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Creates directory ansible
  file:
    path: /opt/nginx/ansible
    state: directory

- name: Install php-fpm
  ansible.builtin.package:
    name: php-fpm
    state: present

- name: Place nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
    mode: "0644"
  notify:
    - Restart nginx

- name: Sets Up PHP Info Page
  ansible.builtin.template:
    src: info.php.j2
    dest: "{{ ansible_folder }}/info.php"
    mode: "0644"
  notify:
    - Restart nginx

- name: Ensure /etc/nginx/conf.d exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: "0755"

- name: Place default.conf
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify:
    - Restart nginx

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
