---
- name: Create group
  group:
    name: "{{ admin_group }}"
    state: present
  become: true

- name: Create Users Task
  user:
    name: "{{ item }}"
    state: present
    password: "{{ userpass | password_hash('sha512','A512') }}"
    shell: /bin/bash
    group: "{{ admin_group }}"
  with_items: "{{ users }}"
  become: true

- name: Deploy SSH Public Key
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/home/anchor/key_pub/id_rsa.pub') }}"
  with_items: "{{ users }}"

- name: Add user to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{ item }}"
    content: "{{ item }}  ALL=(ALL)  NOPASSWD: ALL"
  with_items: "{{ users }}"
  notify:
    - restart ssh
  become: true
