# meta file
---
galaxy_info:
  role_name: postfix
  description: Set up a postfix server in Debian-like systems
  min_ansible_version: 2.9.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - system
    - web
dependencies: []
