---
- name: Create New User
  hosts: all
  become: true
  gather_facts: false
  vars:
# Define your username and password here that you want to create on target hosts.
    users: user1
   
    userpass: 'Abc_1234'
    super_group: anchor

  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        groups: "{{ super_group }}"
        append: yes
     
    - name: Add user to the sudoers
      copy:
        dest: "/etc/sudoers.d/{{ username }}"
        content: "{{ username }}  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/anchor/key_pub/id_rsa.pub') }}"
