- hosts: sf_hwork
  become: True
  roles:
    - role: vsftpd
  tags: deploy_vsftpd
  roles:
    - role: nginx
    - role: dnsmasq
  tags: deploy_nginx
  roles:
    - role: php_fpm
  tags: deploy_user

- hosts: sf_postfix
  become: True
  roles:
    - role: postfix
  tags: deploy_postfix

